### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by kanishka-azimi** [qfpl/sv#14]
Is this library ready for production use or is it still in beta?

**Comment by gwils** [comment]
Good question! I intend to blog soon about where sv is at and a roadmap for where we could go. I'll try to write a quick summary here:

- I consider the Parse and Decode aspects of sv ready for real-world use. They are tested and benchmarked sufficiently in my opinion. Parsing with trifecta (the default) is something like 10-20x slower than cassava and parsing using attoparsec is something like 5-10x slower than cassava. If this performance hit matters to you, consider using [sv-cassava](http://hackage.haskell.org/package/sv-cassava) to borrow cassava's parsing speed.
- The Encode and Print phases are tested but have not been benchmarked, so I don't know whether they perform reasonably. I would like to test them more too.
- The API is subject to change in future. Releases will follow the [PVP](https://pvp.haskell.org/), so you can keep yourself safe by specifying appropriate upper bounds.
- Streaming is missing, so sv can't handle very large files. I have run it successfully on 30MB files. I don't know what the breaking point is.

If you do use sv in production, please let me know how it goes and whether you have any issues :)

**Comment by kanishka-azimi** [comment]
Thanks!

I went back to forking cassava for production for now. I just need named record style parsing for my particular task, otherwise I would be have tried sv. I will watch the other issue tracing named record parsing.
