### ISSUE TITLE
All parses given field parsers

### ISSUE THREAD

**Issue by kanishka-azimi** [qfpl/sv#15]
Use earley to allow for ambiguous parsing, and list out all possible parses given a list of field parsers

**Comment by gwils** [comment]
Could you please elaborate more on what you want here?
Do you want the ability to turn an Earley parser into a 'Decode'?

**Comment by kanishka-azimi** [comment]
I'll close this for now, reopen when I am actively considering implementing a feature that might use ambiguous parsing. (Yes, something that uses or feels like Earley for converting from SV into a tuple or record, where different columns get mapped to the records fields in different parses)
